image: python:3.8.10

stages:          # List of stages for jobs, and their order of execution
  - test
  - deploy

before_script:
  - python --version
  - pip install -r requirements.txt

test:   
  stage: test    
  script:
    - pwd
    - python -m pytest




deploy-job:      
  stage: deploy  
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
